import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Case Study Next 15',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <main className="container">{children}</main>
      </body>
    </html>
  )
}
